const leads=[
 {id:'ES-20260826-00001',name:'Rahul Sharma',route:'Thane → Pune',source:'Google Ads',partner:'Company A',status:'Booking Confirmed',value:'₹18,500'},
 {id:'ES-20260826-00002',name:'Priya Mehta',route:'Mulund → Navi Mumbai',source:'Superfone',partner:'Company B',status:'Quotation Sent',value:'₹24,000'},
 {id:'ES-20260826-00003',name:'Amit Shah',route:'Thane → Mumbai',source:'Meta Ads',partner:'Company C',status:'Contacted',value:'—'},
 {id:'ES-20260826-00004',name:'Neha Gupta',route:'Dombivli → Pune',source:'Google Ads',partner:'Company A',status:'New',value:'—'},
];
const partners=[{name:'Company A',leads:420,bookings:128,rate:'30.5%',revenue:'₹8.10L',width:'76%'},{name:'Company B',leads:390,bookings:92,rate:'23.6%',revenue:'₹5.60L',width:'59%'},{name:'Company C',leads:438,bookings:92,rate:'21.0%',revenue:'₹5.05L',width:'53%'}];
function statusClass(s:string){if(s==='Booking Confirmed'||s==='Move Completed')return 'green';if(s==='Quotation Sent'||s==='Contacted')return 'blue';if(s==='New'||s==='Assigned')return 'orange';return 'gray'}
export default function Home(){return <div className="app"><aside className="sidebar"><div className="brand">Easy Shift CRM<small>Lead Distribution System</small></div><nav className="nav"><div className="active">Dashboard</div><div>Leads</div><div>Calls</div><div>Partners</div><div>Assignments</div><div>Conversions</div><div>Reports</div><div>Users</div><div>Settings</div></nav></aside><main className="main"><header className="top"><div className="title"><h1>Dashboard</h1><p>Central control center for Easy Shift leads</p></div><div className="admin">Super Admin · Easy Shift</div></header><section className="grid"><Metric label="Total Leads" value="1,248" note="+12.4% this month"/><Metric label="Today's Leads" value="18" note="6 from Google Ads"/><Metric label="Unassigned" value="3" note="Needs attention" warn/><Metric label="Bookings" value="128" note="₹18.75L value"/></section><section className="section"><div className="section-head"><h2>Recent Leads</h2><span className="link">View all leads →</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Lead</th><th>Customer</th><th>Route</th><th>Source</th><th>Partner</th><th>Status</th><th>Value</th></tr></thead><tbody>{leads.map(l=><tr key={l.id}><td><strong>{l.id}</strong></td><td>{l.name}</td><td>{l.route}</td><td>{l.source}</td><td>{l.partner}</td><td><span className={'status '+statusClass(l.status)}>{l.status}</span></td><td>{l.value}</td></tr>)}</tbody></table></div></section><section className="section"><div className="section-head"><h2>Partner Performance</h2><span className="link">View reports →</span></div><div className="partner-grid">{partners.map(p=><div className="card partner" key={p.name}><h3>{p.name}</h3><div className="partner-row"><span>Leads</span><strong>{p.leads}</strong></div><div className="partner-row"><span>Bookings</span><strong>{p.bookings}</strong></div><div className="partner-row"><span>Booking rate</span><strong>{p.rate}</strong></div><div className="bar"><span style={{width:p.width}}/></div><div className="partner-row"><span>Revenue</span><strong>{p.revenue}</strong></div></div>)}</div></section><section className="section"><div className="section-head"><h2>System status</h2></div><div className="grid"><System name="Database / Supabase" state="Ready"/><System name="WordPress Lead API" state="Pending setup"/><System name="Superfone" state="Pending setup"/><System name="Google + Meta" state="Pending setup"/></div></section></main></div>}
function Metric({label,value,note,warn=false}:{label:string,value:string,note:string,warn?:boolean}){return <div className="card"><div className="metric-label">{label}</div><div className="metric">{value}</div><div className="metric-note" style={warn?{color:'#b26b00'}:{}}>{note}</div></div>}
function System({name,state}:{name:string,state:string}){return <div className="card"><div className="metric-label">{name}</div><div style={{marginTop:10,fontWeight:700}}><span className={'status '+(state==='Ready'?'green':'gray')}>{state}</span></div></div>}