import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { assignLead, createLead, unassignLead, updateLeadStatus } from './actions'

type Lead = { id:string; lead_number:string; name:string; mobile:string; alternate_mobile:string|null; email:string|null; pickup_location:string|null; drop_location:string|null; moving_date:string|null; service_type:string|null; property_size:string|null; source:string; source_detail:string|null; status:string; assigned_company_id:string|null; quote_amount:number|null; booking_value:number|null; next_followup_at:string|null; notes:string|null; created_at:string }
type Company = { id:string; name:string; company_code:string; status:string; is_owner:boolean }
const statuses = ['new','assigned','contacted','interested','quotation_sent','booking_confirmed','move_completed','lost','cancelled']
const sources = ['google_ads','meta_ads','organic','direct','referral','superfone','manual','other']

function label(value:string) { return value.replaceAll('_',' ').replace(/\b\w/g, c => c.toUpperCase()) }

export default async function LeadsPage() {
  const supabase = await createClient()
  const { data:{ user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')
  const { data: profileRows } = await supabase.rpc('get_my_profile')
  const profile = profileRows?.[0]
  if (!profile || profile.status !== 'active') redirect('/login')
  const isAdmin = profile.role === 'super_admin'

  const { data: leadsData } = await supabase.from('leads').select('id,lead_number,name,mobile,alternate_mobile,email,pickup_location,drop_location,moving_date,service_type,property_size,source,source_detail,status,assigned_company_id,quote_amount,booking_value,next_followup_at,notes,created_at').order('created_at',{ascending:false})
  const leads = (leadsData ?? []) as Lead[]
  const { data: companiesData } = isAdmin ? await supabase.from('companies').select('id,name,company_code,status,is_owner').eq('status','active').order('is_owner',{ascending:false}).order('name') : { data: [] as Company[] }
  const companies = (companiesData ?? []) as Company[]
  const companyMap = new Map(companies.map(c => [c.id,c.name]))

  return <div className="app"><aside className="sidebar"><div className="brand">Easy Shift CRM<small>Lead Distribution System</small></div><nav className="nav"><a href="/">Dashboard</a><a className="active" href="/leads">Leads</a><a href="/calls">Calls</a><a href="/partners">Partners</a><a href="/assignments">Assignments</a><a href="/conversions">Conversions</a><a href="/reports">Reports</a><a href="/users">Users</a><a href="/settings">Settings</a></nav></aside>
  <main className="main"><header className="top"><div className="title"><h1>Leads</h1><p>{isAdmin ? 'All Easy Shift leads and assignments' : 'Leads assigned to your company'}</p></div><div className="admin-wrap"><div className="admin">{profile.full_name} · {label(profile.role)}</div><form action="/auth/signout" method="post"><button className="signout" type="submit">Sign out</button></form></div></header>

  {isAdmin && <section className="section"><div className="section-head"><h2>Add New Lead</h2><span className="link">Super Admin only</span></div><div className="card"><form action={createLead} className="partner-form"><div><label>Customer name *</label><input name="name" required placeholder="Customer name" /></div><div><label>Mobile *</label><input name="mobile" required inputMode="tel" pattern="[0-9]{10}" maxLength={10} placeholder="10 digit mobile" /></div><div><label>Alternate mobile</label><input name="alternate_mobile" inputMode="tel" pattern="[0-9]{10}" maxLength={10} placeholder="Optional" /></div><div><label>Email</label><input name="email" type="email" placeholder="Optional" /></div><div><label>Pickup</label><input name="pickup_location" placeholder="Pickup location" /></div><div><label>Drop</label><input name="drop_location" placeholder="Drop location" /></div><div><label>Moving date</label><input name="moving_date" type="date" /></div><div><label>Service type</label><input name="service_type" placeholder="Home / Office / Vehicle" /></div><div><label>Property size</label><input name="property_size" placeholder="1 BHK / 2 BHK / Office" /></div><div><label>Lead source</label><select name="source" defaultValue="manual">{sources.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></div><div><label>Source detail</label><input name="source_detail" placeholder="Campaign / keyword / referral" /></div><div><label>Notes</label><input name="notes" placeholder="Initial notes" /></div><div className="form-end"><button className="primary" type="submit">Create Lead</button></div></form></div></section>}

  <section className="section"><div className="section-head"><h2>Lead List</h2><span className="link">{leads.length} leads</span></div><div className="partner-list">{leads.length===0 ? <div className="card"><p className="muted">No leads yet. Create your first lead above.</p></div> : leads.map(lead => <div className="card" key={lead.id}><div className="partner-admin-head"><div><h3>{lead.name}</h3><span className="status gray">{lead.lead_number}</span></div><span className={'status '+(['booking_confirmed','move_completed'].includes(lead.status)?'green':lead.status==='cancelled'||lead.status==='lost'?'gray':'blue')}>{label(lead.status)}</span></div><div className="partner-form compact"><div><label>Mobile</label><input readOnly value={lead.mobile}/></div><div><label>Route</label><input readOnly value={[lead.pickup_location,lead.drop_location].filter(Boolean).join(' → ')}/></div><div><label>Moving date</label><input readOnly value={lead.moving_date || ''}/></div><div><label>Source</label><input readOnly value={label(lead.source)}/></div><div><label>Assigned company</label><input readOnly value={lead.assigned_company_id ? (companyMap.get(lead.assigned_company_id) || 'Assigned company') : 'Unassigned'}/></div><div><label>Created</label><input readOnly value={new Date(lead.created_at).toLocaleString('en-IN')}/></div>{!isAdmin ? <div><form action={updateLeadStatus}><input type="hidden" name="id" value={lead.id}/><label>Status</label><select name="status" defaultValue={lead.status}>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select><button className="secondary" type="submit">Update Status</button></form></div> : <><div><form action={updateLeadStatus}><input type="hidden" name="id" value={lead.id}/><label>Status</label><select name="status" defaultValue={lead.status}>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select><button className="secondary" type="submit">Update Status</button></form></div><div><form action={assignLead}><input type="hidden" name="lead_id" value={lead.id}/><label>Assign to</label><select name="company_id" defaultValue={lead.assigned_company_id || ''} required><option value="" disabled>Select company</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="secondary" type="submit">Assign Lead</button></form></div>{lead.assigned_company_id && <div className="form-end"><form action={unassignLead}><input type="hidden" name="lead_id" value={lead.id}/><button className="secondary" type="submit">Unassign</button></form></div>}</>}</div>{lead.notes && <p className="muted" style={{marginTop:12}}>Notes: {lead.notes}</p>}</div>)}</div></section>
  </main></div>
}
